project: "Pandemic Response Repository"
name: pandemic-response-repository
github:
- newamericafoundation/pandemic-response-repository
description: Pandemic Response Repository is a maintained list of open source projects usable by governments.
stage: beta
milestones:
contact:
- newamericafoundation/pandemic-response-repository/issues
team: marklerner
licenses:
  pandemic-response-repository: CC-BY-4.0
links:
- https://newamericafoundation.github.io/pandemic-response-repository/
blog:

status:
