markdown: kramdown
kramdown:
  parse_block_html: true
name: Pandemic Response Repository
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- go
- vendor

permalink: pretty
highlighter: rouge

sass:
  style: compressed

site:
  title: Pandemic Response Repository

page_gen:
  - data: 'projects'
    template: 'projects'
    name: 'title'

description: Pandemic Response Repository is a maintained list of open source projects usable by governments.

baseurl: /open-covid

repos:
- name: Pandemic Response Repository
  description: Main repository
  url: https://github.com/newamericafoundation/pandemic-response-repository

jekyll_get:
  - data: releases
    json: 'https://api.github.com/repos/newamericafoundation/pandemic-response-repository/releases'

plugins:
  - jekyll-last-modified-at
  - jemoji
  - jekyll-mentions
  - jekyll-redirect-from
#  - jekyll-datapage-generator
